export const actionTypes = {
// ACCOUNT ACTIONS
    // POST Login:
    POST_LOGIN_START: "POST_LOGIN_START",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
    // POST REGISTER:
    POST_REGISTER_START: "POST_REGISTER_START",
    POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
    POST_REGISTER_FAIL: "POST_REGISTER_FAIL",
// COLOR ACTIONS
    // FETCH COLORS:
    FETCH_COLORS_START: "FETCH_COLORS_START",
    FETCH_COLORS_SUCCESS: "FETCH_COLORS_SUCCESS",
    FETCH_COLORS_FAIL: "FETCH_COLORS_FAIL",
// TASK ACTIONS
    // FETCH TASKS:
    FETCH_TASKS_START: "FETCH_TASKS_START",
    FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
    FETCH_TASKS_FAIL: "FETCH_TASKS_FAIL",
    // POST TASK:
    POST_TASK_START: "POST_TASK_START",
    POST_TASK_SUCCESS: "POST_TASK_SUCCESS",
    POST_TASK_FAIL: "POST_TASK_FAIL",
    // DELETE TASK:
    DELETE_TASK_START: "DELETE_TASK_START",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAIL: "DELETE_TASK_FAIL",
// AGENDA ACTIONS
    // FETCH AGENDAS:
    FETCH_AGENDAS_START: "FETCH_AGENDAS_START",
    FETCH_AGENDAS_SUCCESS: "FETCH_AGENDAS_SUCCESS",
    FETCH_AGENDAS_FAIL: "FETCH_AGENDAS_FAILS",
    // POST AGENDA
    POST_AGENDA_START: "POST_AGENDA_START",
    POST_AGENDA_SUCCESS: "POST_AGENDA_SUCCESS",
    POST_AGENDA_FAIL: "POST_AGENDA_FAIL",
    // DELETE AGENDA:
    DELETE_AGENDA_START: "DELETE_AGENDA_START",
    DELETE_AGENDA_SUCCESS: "DELETE_AGENDA_SUCCESS",
    DELETE_AGENDA_FAIL: "DELETE_AGENDA_FAIL",
// APP STATE ACTIONS
    // MOVE MONTH:
    MOVE_MONTH_FORWARD: "MOVE_MONTH_FORWARD",
    MOVE_MONTH_BACKWARD: "MOVE_MONTH_BACKWARD",
    // UPDATE NAME:
    UPDATE_MONTH_NAME: "UPDATE_MONTH_NAME",
    // POP AGENDAS:
    SET_POP_AGENDAS: "SET_POP_AGENDAS",
    // POP STATE:
    SET_POP_STATE: "SET_POP_STATE",
}